import { readFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname } from 'node:path'
import { addComponent, addImports, defineNuxtModule, useLogger } from '@nuxt/kit'

const require = createRequire(import.meta.url)
const logger = useLogger('@fyrst/ui')

function resolveFromPackage(specifier: string): string | undefined {
  try {
    return require.resolve(specifier)
  }
  catch {
    return undefined
  }
}

function resolveIconCss(): string | undefined {
  return resolveFromPackage('@fyrst/ui/style.css')
}

function readModuleVersion(): string {
  try {
    const pkgPath = require.resolve('@fyrst/ui/package.json')
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf8')) as { version?: string }
    return pkg.version ?? '0.0.0'
  }
  catch {
    return '0.0.0'
  }
}

function loadNuxtEntries(): {
  components: Record<string, string>
  composables: string[]
} {
  const entriesPath = resolveFromPackage('@fyrst/ui/nuxt-entries.json')

  if (!entriesPath) {
    return { components: {}, composables: [] }
  }

  return JSON.parse(readFileSync(entriesPath, 'utf8')) as {
    components: Record<string, string>
    composables: string[]
  }
}

function resolveVueFile(entryName: string): string | undefined {
  return resolveFromPackage(`@fyrst/ui/vue/${entryName}`)
}

function resolveComponentsDist(): string | undefined {
  const entriesPath = resolveFromPackage('@fyrst/ui/nuxt-entries.json')
  return entriesPath ? dirname(entriesPath) : undefined
}

function hasPandaPostcssPlugin(postcss: { plugins?: Record<string, unknown> } | undefined): boolean {
  const plugins = postcss?.plugins
  if (!plugins) {
    return false
  }
  return Object.prototype.hasOwnProperty.call(plugins, '@pandacss/dev/postcss')
}

function warnIfPandaSetupLooksMissing(nuxt: { options: { dev: boolean, postcss?: { plugins?: Record<string, unknown> } } }) {
  if (!resolveFromPackage('@fyrst/ui/panda.buildinfo.json')) {
    logger.warn('Could not resolve @fyrst/ui/panda.buildinfo.json. Include require.resolve(\'@fyrst/ui/panda.buildinfo.json\') in panda.config.ts so component styles generate.')
  }

  if (nuxt.options.dev && !hasPandaPostcssPlugin(nuxt.options.postcss)) {
    logger.warn('Panda PostCSS is not configured. Set postcss.plugins[\'@pandacss/dev/postcss\'] in nuxt.config and keep @layer reset, base, tokens, recipes, utilities in your CSS.')
  }
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

function allowLinkedFsDir(
  vite: { server?: { fs?: { allow?: string[] } } },
  dir: string | undefined,
) {
  if (!dir) {
    return
  }

  vite.server ??= {}
  vite.server.fs ??= {}
  vite.server.fs.allow ??= []
  if (!vite.server.fs.allow.includes(dir)) {
    vite.server.fs.allow.push(dir)
  }
}

function excludeLinkedVueDist(
  imports: { transform?: { exclude?: RegExp[] } },
  dir: string | undefined,
) {
  if (!dir) {
    return
  }

  imports.transform ??= {}
  imports.transform.exclude ??= []
  const pattern = new RegExp(escapeRegExp(dir))
  if (!imports.transform.exclude.some(existing => existing.source === pattern.source)) {
    imports.transform.exclude.push(pattern)
  }
}

export interface ModuleOptions {
  /**
   * Prefix for auto-registered components.
   * `Button` becomes `FyrstButton` when prefix is `Fyrst`.
   * @default 'Fyrst'
   */
  prefix?: string
  /**
   * Inject the icon stylesheet from `@fyrst/ui`.
   * Component styles are generated by Panda CSS in the consuming app
   * from `@fyrst/ui/panda.buildinfo.json`.
   * @default true
   */
  icons?: boolean
}

export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: '@fyrst/ui',
    configKey: 'fyrstUi',
    version: readModuleVersion(),
  },
  defaults: {
    prefix: 'Fyrst',
    icons: true,
  },
  setup(options, nuxt) {
    const prefix = options.prefix ?? 'Fyrst'
    const { components, composables } = loadNuxtEntries()

    nuxt.options.build.transpile.push('reka-ui')

    const componentsDist = resolveComponentsDist()
    allowLinkedFsDir(nuxt.options.vite, componentsDist)
    excludeLinkedVueDist(nuxt.options.imports, componentsDist)
    warnIfPandaSetupLooksMissing(nuxt)

    if (options.icons !== false) {
      const cssPath = resolveIconCss()
      if (cssPath) {
        if (!nuxt.options.css.includes(cssPath)) {
          nuxt.options.css.push(cssPath)
        }
        allowLinkedFsDir(nuxt.options.vite, dirname(cssPath))
      }
      else {
        logger.warn('Could not resolve @fyrst/ui/style.css. Iconify icons will be missing.')
      }
    }

    if (Object.keys(components).length === 0) {
      logger.warn('Could not resolve @fyrst/ui/nuxt-entries.json. Auto-imports are skipped.')
    }

    for (const [name, entry] of Object.entries(components)) {
      const filePath = resolveVueFile(entry)
      if (!filePath) {
        logger.warn(`Could not resolve Vue entry ${entry} for ${prefix}${name}.`)
        continue
      }

      addComponent({
        name: `${prefix}${name}`,
        export: 'default',
        filePath,
      })
    }

    for (const name of composables) {
      const filePath = resolveVueFile(name)
      if (!filePath) {
        logger.warn(`Could not resolve composable ${name}.`)
        continue
      }

      addImports({
        name,
        from: filePath,
      })
    }
  },
})
