import { existsSync } from 'node:fs'
import { createRequire } from 'node:module'
import { fileURLToPath } from 'node:url'
import { addComponent, addImports, createResolver, defineNuxtModule } from '@nuxt/kit'

const require = createRequire(import.meta.url)

function resolveIconCss(): string | undefined {
  try {
    return require.resolve('@fyrst/ui/style.css')
  }
  catch {
    // Root package is not linked in the monorepo; fall through to relative paths.
  }

  const candidates = [
    new URL('../../components/dist/ui-components.css', import.meta.url),
    new URL('../../../components/dist/ui-components.css', import.meta.url),
    new URL('../../../dist/style.css', import.meta.url),
    new URL('../../../../dist/style.css', import.meta.url),
  ]

  for (const url of candidates) {
    try {
      const cssPath = fileURLToPath(url)
      if (existsSync(cssPath)) {
        return cssPath
      }
    }
    catch {
      // ignore
    }
  }

  return undefined
}

const vueComponents = [
  'AccordionRoot',
  'Alert',
  'AlertRoot',
  'Badge',
  'BadgeRoot',
  'Button',
  'CardRoot',
  'CardBody',
  'CardHeader',
  'CarouselRoot',
  'CarouselItem',
  'CarouselNavigation',
  'DialogRoot',
  'FieldInput',
  'FieldTextarea',
  'FieldSelect',
  'FieldCheckbox',
  'FieldRadioGroup',
  'FieldSwitch',
  'FieldUrl',
  'FieldBase',
  'FieldLabel',
  'FieldError',
  'FieldMessage',
  'FieldRequired',
  'FlyoutRoot',
  'FlyoutDropdown',
  'FormPrompt',
  'FormPromptFooter',
  'HeroLead',
  'ListRoot',
  'ListItem',
  'Loader',
  'PricingCardRoot',
  'PricingCardHeader',
  'PricingCardPricing',
  'PricingCardBody',
  'PricingCardBadge',
  'ProgressRoot',
  'SwitchRoot',
  'Tab',
  'TabItem',
] as const

const composables = [
  'useCarousel',
  'useFlyout',
  'useFormData',
  'createInjectionKey',
] as const

export interface ModuleOptions {
  /**
   * Prefix for auto-registered components.
   * `Button` becomes `FyrstButton` when prefix is `Fyrst`.
   * @default 'Fyrst'
   */
  prefix?: string
  /**
   * Inject the icon stylesheet from `@fyrst/ui`.
   * Component styles are generated by Panda CSS in the consuming app
   * from `@fyrst/ui/panda.buildinfo.json`.
   * @default true
   */
  icons?: boolean
}

export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: '@fyrst/ui',
    configKey: 'fyrstUi',
    version: '0.1.0',
  },
  defaults: {
    prefix: 'Fyrst',
    icons: true,
  },
  setup(options, nuxt) {
    const resolver = createResolver(import.meta.url)
    const componentsFile = resolver.resolve('./runtime/components')
    const composablesFile = resolver.resolve('./runtime/composables')
    const prefix = options.prefix ?? 'Fyrst'

    nuxt.options.build.transpile.push('reka-ui')

    if (options.icons !== false) {
      const cssPath = resolveIconCss()
      if (cssPath && !nuxt.options.css.includes(cssPath)) {
        nuxt.options.css.push(cssPath)
      }
    }

    for (const name of vueComponents) {
      addComponent({
        name: `${prefix}${name}`,
        export: name,
        filePath: componentsFile,
      })
    }

    for (const name of composables) {
      addImports({
        name,
        from: composablesFile,
      })
    }
  },
})
