import { existsSync, readFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { addComponent, addImports, defineNuxtModule, useLogger } from '@nuxt/kit'

const require = createRequire(import.meta.url)
const logger = useLogger('@fyrst/ui')

function findFileFromModule(relativePaths: string[]): string | undefined {
  let dir = fileURLToPath(new URL('.', import.meta.url))

  for (let i = 0; i < 8; i++) {
    for (const relativePath of relativePaths) {
      const candidate = join(dir, relativePath)
      if (existsSync(candidate)) {
        return candidate
      }
    }

    const parent = dirname(dir)
    if (parent === dir) {
      break
    }
    dir = parent
  }
}

function resolveIconCss(): string | undefined {
  try {
    return require.resolve('@fyrst/ui/style.css')
  }
  catch {
    // Root package is not linked as node_modules/@fyrst/ui until `bun run link:package`.
  }

  return findFileFromModule([
    'dist/style.css',
    'packages/components/dist/ui-components.css',
    'components/dist/ui-components.css',
  ])
}

function readModuleVersion(): string {
  try {
    const pkgPath = fileURLToPath(new URL('../package.json', import.meta.url))
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf8')) as { version?: string }
    return pkg.version ?? '0.0.0'
  }
  catch {
    return '0.0.0'
  }
}

function loadNuxtEntries(): {
  components: Record<string, string>
  composables: string[]
} {
  const entriesPath = findFileFromModule([
    'packages/components/dist/nuxt-entries.json',
    'components/dist/nuxt-entries.json',
  ])

  if (!entriesPath) {
    return { components: {}, composables: [] }
  }

  return JSON.parse(readFileSync(entriesPath, 'utf8')) as {
    components: Record<string, string>
    composables: string[]
  }
}

function resolveVueFile(entryName: string): string | undefined {
  return findFileFromModule([
    `packages/components/dist/vue/${entryName}.js`,
    `components/dist/vue/${entryName}.js`,
  ])
}

function resolveComponentsDist(): string | undefined {
  return findFileFromModule([
    'packages/components/dist',
    'components/dist',
  ])
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

function allowLinkedFsDir(
  vite: { server?: { fs?: { allow?: string[] } } },
  dir: string | undefined,
) {
  if (!dir) {
    return
  }

  vite.server ??= {}
  vite.server.fs ??= {}
  vite.server.fs.allow ??= []
  if (!vite.server.fs.allow.includes(dir)) {
    vite.server.fs.allow.push(dir)
  }
}

function excludeLinkedVueDist(
  imports: { transform?: { exclude?: RegExp[] } },
  dir: string | undefined,
) {
  if (!dir) {
    return
  }

  imports.transform ??= {}
  imports.transform.exclude ??= []
  const pattern = new RegExp(escapeRegExp(dir))
  if (!imports.transform.exclude.some(existing => existing.source === pattern.source)) {
    imports.transform.exclude.push(pattern)
  }
}

export interface ModuleOptions {
  /**
   * Prefix for auto-registered components.
   * `Button` becomes `FyrstButton` when prefix is `Fyrst`.
   * @default 'Fyrst'
   */
  prefix?: string
  /**
   * Inject the icon stylesheet from `@fyrst/ui`.
   * Component styles are generated by Panda CSS in the consuming app
   * from `@fyrst/ui/panda.buildinfo.json`.
   * @default true
   */
  icons?: boolean
}

export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: '@fyrst/ui',
    configKey: 'fyrstUi',
    version: readModuleVersion(),
  },
  defaults: {
    prefix: 'Fyrst',
    icons: true,
  },
  setup(options, nuxt) {
    const prefix = options.prefix ?? 'Fyrst'
    const { components, composables } = loadNuxtEntries()

    nuxt.options.build.transpile.push('reka-ui')

    const componentsDist = resolveComponentsDist()
    allowLinkedFsDir(nuxt.options.vite, componentsDist)
    excludeLinkedVueDist(nuxt.options.imports, componentsDist)

    if (options.icons !== false) {
      const cssPath = resolveIconCss()
      if (cssPath) {
        if (!nuxt.options.css.includes(cssPath)) {
          nuxt.options.css.push(cssPath)
        }
        allowLinkedFsDir(nuxt.options.vite, dirname(cssPath))
      }
      else {
        logger.warn('Could not resolve @fyrst/ui/style.css. Iconify icons will be missing.')
      }
    }

    if (Object.keys(components).length === 0) {
      logger.warn('Could not resolve packages/components/dist/nuxt-entries.json. Auto-imports are skipped.')
    }

    for (const [name, entry] of Object.entries(components)) {
      const filePath = resolveVueFile(entry)
      if (!filePath) {
        logger.warn(`Could not resolve Vue entry ${entry} for ${prefix}${name}.`)
        continue
      }

      addComponent({
        name: `${prefix}${name}`,
        export: 'default',
        filePath,
      })
    }

    for (const name of composables) {
      const filePath = resolveVueFile(name)
      if (!filePath) {
        logger.warn(`Could not resolve composable ${name}.`)
        continue
      }

      addImports({
        name,
        from: filePath,
      })
    }
  },
})
